# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
exclude: ["node_modules/"]


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Global Biotic Interactions
description: > # this means to ignore newlines until "baseurl:"
  Access to species interaction data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://globalbioticinteractions.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
defaults:
  -
    scope: 
      path: ""
    values:
      lang: en
  - 
    scope:
      path: ""
      type: "posts"
    values: 
      permalink: /:year/:month/:day/:title/
  -
    scope:
      path: es
    values:
      lang: es
      base-url: "/es/"

# Value to use into url per language
langs-value:
    en: ""
    es: es

# Translation
t:
    language:
        en: "English"
        es: "Español"
    example-query:
        en: "Example query"
        es: "Por ejemplo"
    what-do-sea-otters-eat:
        en: "What do sea otters (<em>Enhydra lutris</em>) eat?"
        es: "Qué come la nutria (<em>Enhydra lutris</em>)?"
    or:
        en: "or"
        es: "o"
    what-do-honey-bees-pollinate:
        en: "What do honey bees (<em>Apis sp.</em>) pollinate?"
        es: "Qué plantas poliniza la abeja mielera (<em>Apis sp.</em>)?"
    what-kind-of:
        en: "What kind of"
        es: "Qué tipo de"
    do:
        en: "do"
        es: "hace"
    more:
        en: "more"
        es: "más"
    none:
        en: "None"
        es: "Ninguno"
    nothing:
        en: "nothing"
        es: "nada"
    search-suggestion:
        en: >
          nothing that we are aware of. Please make sure to use <a href="https://en.wikipedia.org/wiki/Taxon">scientific taxon names</a> to describe the organism that you are interested in. For instance, instead of searching for "guppy", use <a href="?sourceTaxon=Poecilia%20reticulata"><em>Poecilia reticulata</em></a>.
        es: >
          no encontramos nada. Asegúrate de estar utilizando el <a href="https://es.wikipedia.org/wiki/Taxon">nombre científico</a> del taxón para describir el organismo que te interesa. En lugar de buscar por "Guppy", busca por <a href="?sourceTaxon=Poecilia%20reticulata"><em>Poecilia reticulata</em></a>.
    refuted-by:
        en: "Refuted by"
        es: "Rechazado por"
    supported-by:
        en: "Supported by"
        es: "Aprobado por"
    according-to:
        en: "according to"
        es: "de acuerdo a"
    organisms:
        en: "organisms"
        es: "organismos"
    plenty-of-things:
        en: "plenty of things"
        es: "muchas cosas"
    missing-some-results:
        en: "Missing some results?"
        es: "Falta algún resultado?"
    please-share-your-dataset:
        en: "Please share your dataset!"
        es: "¡Por favor comparte tus datos!"
    have-suggestions:
        en: "Have suggestions?"
        es: "¿Tienes alguna sugerencia?"
    let-us-know:
        en: "Let us know."
        es: "Haznos saber."
    like-a-different-view:
        en: "Like a different view?"
        es: "¿Te gustaría una vista diferente?"
    open-results-in-browser:
        en: "Open results in interaction browser"
        es: "Resultados en el navegador de interacciones"
    list-the-references:
        en: "list the references"
        es: "lista de referencias"
    interacts-with:
        en: "interacts with"
        es: "interactua con"
    relate-to:
        en: "relate to"
        es: "relacionado con"
    eat:
        en: "eat"
        es: "come"
    get-eaten-by:
        en: "get eaten by"
        es: "es comida de"
    preys-on:
        en: "preys on"
        es: "es presa de"
    get-preyed-on-by:
        en: "get preyed on by"
        es: "es depredado por"
    parasitize:
        en: "parasitize"
        es: "es parasito de"
    get-parasitized-by:
        en: "get parasitized by"
        es: "es parasitado por"
    is-symbiont-of:
        en: "is symbiont of"
        es: "es simbionte de"
    visits-flowers-of:
        en: "visits flowers of"
        es: "visita las flores de"
    flowers-visited-by:
        en: "flowers visited by"
        es: "flores visitadas por"
    pollinate:
        en: "pollinate"
        es: "poliniza a"
    get-pollinated-by:
        en: "get pollinated by"
        es: "es polinizado por"
    infect:
        en: "infect"
        es: "infecta a"
    get-infected-by:
        en: "get infected by"
        es: "es infectado por"
    spread:
        en: "spread"
        es: "dispersa a"
    get-spread-by:
        en: "get spread by"
        es: "es dispersado por"
    kill:
        en: "kill"
        es: "mata a"
    is-killed-by:
        en: "is killed by"
        es: "lo mata"
        

