# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
exclude: ["node_modules/"]


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Global Biotic Interactions
description: > # this means to ignore newlines until "baseurl:"
  Access to species interaction data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://globalbioticinteractions.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
defaults:
  -
    scope: 
      path: ""
    values:
      lang: en
  - 
    scope:
      path: ""
      type: "posts"
    values: 
      permalink: /:year/:month/:day/:title/
  -
    scope:
      path: es
    values:
      lang: es
      base-url: "/es/"

# Value to use into url per language
langs-value:
    en: ""
    es: es

# Translation
t:
    language:
        en: "English"
        es: "Español"
    example-query:
        en: "Example query"
        es: "Por ejemplo"
    what-do-sea-otters-eat:
        en: "What do sea otters (<em>Enhydra lutris</em>) eat?"
        es: "Que come la nutria (<em>Enhydra lutris</em>)?"
    or:
        en: "or"
        es: "o"
    what-do-honey-bees-pollinate:
        en: "What do honey bees (Apis) pollinate?"
        es: "Que plantas poliniza la abeja mielera (Apis)?"
    what-kind-of:
        en: "What kind of"
        es: "Que tipo de"
    do:
        en: "do"
        es: "hace"
    more:
        en: "more"
        es: "more"
    none:
        en: "none"
        es: "none"
    refuted-by:
        en: "Refuted by"
        es: "Refuted by"
    supported-by:
        en: "Supported by"
        es: "Refuted by"
    according-to:
        en: "according to"
        es: "de acuerdo a"
    organisms:
        en: "organisms"
        es: "organismos"
    plenty-of-things:
        en: "plenty of things"
        es: "plenty of things"
    missing-some-results:
        en: "Missing some results?"
        es: "Missing some results?"
    please-share-your-dataset:
        en: "Please share your dataset!"
        es: "Please share your dataset!"
    have-suggestions:
        en: "Have suggestions?"
        es: "Have suggestions?"
    let-us-know:
        en: "Let us know."
        es: "Let us know."
    like-a-different-view:
        en: "Like a different view?"
        es: "Like a different view?"
    open-results-in-browser:
        en: "Open results in interaction browser"
        es: "Open results in interaction browser"
    list-the-references:
        en: "list the references"
        es: "list the references"
    interacts-with:
        en: "interacts with"
        es: "interacts with"
    relate-to:
        en: "relate to"
        es: "relate to"
    eat:
        en: "eat"
        es: "eat"
    get-eaten-by:
        en: "get eaten by"
        es: "get eaten by"
    preys-on:
        en: "preys on"
        es: "preys on"
    get-preyed-on-by:
        en: "get preyed on by"
        es: "get preyed on by"
    parasitize:
        en: "parasitize"
        es: "parasitize"
    get-parasitized-by:
        en: "get parasitized by"
        es: "get paratisized by"
    is-symbiont-of:
        en: "is symbiont of"
        es: "is symbiont of"
    visits-flowers-of:
        en: "visits flowers of"
        es: "visits flowers of"
    flowers-visited-by:
        en: "flowers visited by"
        es: "flowers visited by"
    pollinate:
        en: "pollinate"
        es: "pollinate"
    get-pollinated-by:
        en: "get pollinated by"
        es: "get pollinated by"
    infect:
        en: "infect"
        es: "infect"
    get-infected-by:
        en: "get infected by"
        es: "get infected by"
    spread:
        en: "spread"
        es: "spread"
    get-spread-by:
        en: "get spread by"
        es: "get spread by"
    kill:
        en: "kill"
        es: "kill"
    is-killed-by:
        en: "is killed by"
        es: "is killed by"
        

