# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
exclude: ["node_modules/"]


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Global Biotic Interactions
description: > # this means to ignore newlines until "baseurl:"
  Access to species interaction data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://globalbioticinteractions.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
defaults:
  -
    scope: 
      path: ""
    values:
      lang: en
  - 
    scope:
      path: ""
      type: "posts"
    values: 
      permalink: /:year/:month/:day/:title/
  -
    scope:
      path: es
    values:
      lang: es
      base-url: "/es/"
  -
    scope:
      path: jp
    values:
      lang: jp
      base-url: "/jp/"

# Value to use into url per language
langs-value:
    en: ""
    es: es
    jp: jp

# Translation
t:
    language:
        en: "English"
        jp: "日本語"
        es: "Español"
    example-query:
        en: "Example query"
        jp: "検索の例"
        es: "Por ejemplo"
    what-do-sea-otters-eat:
        en: "What do sea otters (<em>Enhydra lutris</em>) eat?"
        jp: "ラッコ (<em>Enhydra lutris</em>) は何を食べますか?"
        es: "Qué come la nutria (<em>Enhydra lutris</em>)?"
    or:
        en: "or"
        jp: "あるいは"
        es: "o"
    what-do-honey-bees-pollinate:
        en: "What do honey bees (<em>Apis</em>) pollinate?"
        jp: "ミツバチ (<em>Apis</em>)は、何に受粉しますか?"
        es: "Qué plantas poliniza la abeja mielera (<em>Apis</em>)?"
    what-kind-of:
        en: "What kind of"
        jp: "どんな種類の"
        es: "Qué tipo de"
    do:
        en: "do"
        jp: "する"
        es: "hace"
    more:
        en: "more"
        jp: "より多くの"
        es: "más"
    none:
        en: "None"
        jp: "無し"
        es: "Ninguno"
    nothing:
        en: "nothing"
        jp: "何も無い"
        es: "nothing"
    footer-text:
        en: >
          Global Biotic Interactions is an <a href="http://opendefinition.org/ossd/" title="open service definition">open service</a> providing <a href="http://opendefinition.org/od/" title="open data definition">open data</a> using <a href="https://opensource.org/osd" title="open source definition">open source</a> software.
　　　　 jp: >
          Global Biotic Interactions　は、 <a href="http://opendefinition.org/ossd/" title="open service definition">オープン・サービス</a> を提供しています <a href="http://opendefinition.org/od/" title="open data definition">オープン・データ</a> と <a href="https://opensource.org/osd" title="open source definition">オープンソース</a> を利用したソフトウェアです.     
        es: >
          GloBI es una iniciativa <a href="http://opendefinition.org/ossd/" title="open service definition"> abierta</a> que promueve <a href="http://opendefinition.org/od/" title="open data definition"> datos abiertos</a> utilizando <a href="https://opensource.org/osd" title="open source definition">código abierto</a> para su funcionamiento.
    search-suggestion:
        en: >
          nothing that we are aware of. Please make sure to use <a href="https://en.wikipedia.org/wiki/Taxon">scientific taxon names</a> to describe the organism that you are interested in. For instance, instead of searching for "guppy", use <a href="?sourceTaxon=Poecilia%20reticulata"><em>Poecilia reticulata</em></a>.
        jp: >
          該当しません. 関心がある生物を検索する際に、必ず　<a href="https://en.wikipedia.org/wiki/Taxon">学名</a> を使用してください。例えば、”グッピー”という熱帯魚と入力する代わりに、学名である<a href="?sourceTaxon=Poecilia%20reticulata"><em>Poecilia reticulata</em></a>を入力してください.        
        es: >
          nothing that we are aware of. Please make sure to use <a href="https://en.wikipedia.org/wiki/Taxon">scientific taxon names</a> to describe the organism that you are interested in. For instance, instead of searching for "guppy", use <a href="?sourceTaxon=Poecilia%20reticulata"><em>Poecilia reticulata</em></a>.
    refuted-by:
        en: "Refuted by"
        jp: "反論"
        es: "Rechazado por"
    supported-by:
        en: "Supported by"
        jp: "支持"
        es: "Aprobado por"
    according-to:
        en: "according to"
        jp: "によると"
        es: "de acuerdo a"
    organisms:
        en: "organisms"
        es: "organismos"
        jp: "生物"
    any-study-or-source:
        en: "any study or source"
        jp: "どんな研究 または 情報源"
        es: "any study or source"
    plenty-of-things:
        en: "plenty of things"
        jp: "たくさん存在します"
        es: "muchas cosas"
    missing-some-results:
        en: "Missing some results?"
        jp: "結果が見つかりません"
        es: "Falta algún resultado?"
    please-share-your-dataset:
        en: "Please share your dataset!"
        jp: "あなたのデータセットを是非共有してください!"
        es: "¡Por favor comparte tus datos!"
    have-suggestions:
        en: "Have suggestions?"
        jp: "提案がありますか?"
        es: "¿Tienes alguna sugerencia?"
    let-us-know:
        en: "Let us know."
        jp: "我々にお知らせください."
        es: "Haznos saber."
    like-a-different-view:
        en: "Like a different view?"
        en: "別のビューの方が良いですか?"
        es: "¿Te gustaría una vista diferente?"
    open-results-in-browser:
        en: "Open results in interaction browser"
        jp: "インタラクション・ブラウザーの結果を開いてください。"
        es: "Resultados en el navegador de interacciones"
    list-the-references:
        en: "list the references"
        en: "参照情報をリストします"
        es: "lista de referencias"
    lookup-term-definition-for:
        en: "lookup term definition for"
        jp: "検索用語の定義"
        es: "lookup term definition for"
    interactsWith:
        en: "interacts with"
        jp: "相互作用する"
        es: "interactua con"
    interacts-with:
        en: "interacts with"
        jp: "相互作用する"
        es: "interactua con"
    relate-to:
        en: "relate to"
        jp: "と関連する"
        es: "relacionado con"
    eat:
        en: "eat"
        jp: "食べる（捕食）"
        es: "come"
    eats:
        en: "eats"
        jp: "食べる（捕食）"
        es: "eats"
    eatenBy:
        en: "eaten by"
        jp: "食われる（被食）"
        es: "eaten by"
    get-eaten-by:
        en: "get eaten by"
        jp: "食われる（被食）"
        es: "es comida de"
    preys-on:
        en: "preys on"
        jp: "を捕食する"
        es: "es presa de"
    preysOn:
        en: "preys on"
        jp: "を捕食する"
        es: "es presa de"
    get-preyed-on-by:
        en: "get preyed on by"
        jp: "に食われる"
        es: "es depredado por"
    preyedUponBy:
        en: "preyed upon by"
        jp: "よって食われる"
        es: "preyed upon by"
    kills:
        en: "kills"
        jp: "を殺す"
        es: "kills"
    killedBy:
        en: "killedBy"
        jp: "によって殺される"
        es: "killedBy"
    parasiteOf:
        en: "parasite of"
        jp: "の寄生虫”
        es: "parasite of"
    hasParasite:
        en: "has parasite"
        jp: "寄生虫を持っている"
        es: "has parasite"
    hostOf:
        en: "host of"
        jp: "の宿主"
        es: "host of"
    hasHost:
        en: "has host"
        jp: "宿主を持つ"
        es: "has host"
    parasitize:
        en: "parasitize"
        jp: "に寄生する"
        es: "es parasito de"
    get-parasitized-by:
        en: "get parasitized by"
        jp: "に寄生される"
        es: "es parasitado por"
    is-symbiont-of:
        en: "is symbiont of"
        jp: "の共生です"
        es: "es simbionte de"
    visitsFlowersOf:
        en: "visits flowers of"
        jp: "を訪花する"
        es: "visita las flores de"
    visits-flowers-of:
        en: "visits flowers of"
        jp: "を訪花する"
        es: "visita las flores de"
    flowersVisitedBy:
        en: "flowers visited by"
        jp: "によって訪花される"
        es: "flores visitadas por" 
    flowers-visited-by:
        en: "flowers visited by"
        jp: "によって訪花される"
        es: "flores visitadas por"
    pollinates:
        en: "pollinates"
        jp: "を受粉する"
        es: "pollinates"
    pollinate:
        en: "pollinate"
        jp: "を受粉する"
        es: "poliniza a"
    pollinatedBy:
        en: "pollinated by"
        jp: "によって受粉される"
        es: "pollinated by"
    get-pollinated-by:
        en: "get pollinated by"
        jp: "によって受粉される"
        es: "es polinizado por"
    pathogenOf:
        en: "pathogen of"
        jp: "の病原体"
        es: "pathogen of"
    hasPathogen:
        en: "has pathogen"
        jp: "病原体を持っている"
        es: "has pathogen"
    vectorOf:
        en: "vector of"
        jp: "のベクター"
        es: "vector of"
    hasVector:
        en: "has vector"
        jp: "ベクターを持っている"
        es: "has vector"
    dispersalVectorOf:
        en: "dispersal vector of"
        jp: "の拡散ベクター"
        es: "dispersal vector of"
    hasDispersalVector:
        en: "has dispersal vector"
        jp: "拡散ベクターを持っている"
        es: "has dispersal vector"
    symbiontOf:
        en: "symbiont of"
        jp: "の共生"
        es: "symbiont of"
    ecologicallyRelatedTo:
        en: "related to"
        jp: "と関連する"
        es: "related to"
    coOccursWith:
        en: "co-occurs with"
        jp: "と共起する"
        es: "co-occurs with"
    infect:
        en: "infect"
        jp: "に感染する"
        es: "infecta a"
    get-infected-by:
        en: "get infected by"
        jp: "によって感染される"
        es: "es infectado por"
    spread:
        en: "spread"
        jp: "伝播する"
        es: "dispersa a"
    get-spread-by:
        en: "get spread by"
        jp: "によって広がる"
        es: "es dispersado por"
    kill:
        en: "kill"
        jp: "を殺す"
        es: "mata a"
    is-killed-by:
        en: "is killed by"
        jp: "によって殺される"
        es: "lo mata"
        

